var searchData=
[
  ['safety_0',['Thread Safety',['../index.html#doc_cc_mqttsn_client_thread_safety',1,'']]],
  ['search_20broadcast_20radius_1',['Configuring &quot;Search&quot; Broadcast Radius',['../index.html#doc_cc_mqttsn_client_search_broadcast_radius',1,'']]],
  ['search_20gateway_20request_2',['Sending Search Gateway Request',['../index.html#doc_cc_mqttsn_client_search_send',1,'']]],
  ['search_20operation_3',['search operation',['../index.html#doc_cc_mqttsn_client_search_cancel',1,'Cancel the &quot;Search&quot; Operation.'],['../index.html#doc_cc_mqttsn_client_search_prepare',1,'Preparing &quot;Search&quot; Operation.']]],
  ['search_20operation_20data_20types_20and_20functions_4',['&quot;Search Operation Data Types and Functions&quot;',['../group__search.html',1,'']]],
  ['search_20operation_20preparation_5',['Simplifying the &quot;Search&quot; Operation Preparation',['../index.html#doc_cc_mqttsn_client_search_simplify',1,'']]],
  ['search_20retry_20count_6',['Configuring &quot;Search&quot; Retry Count',['../index.html#doc_cc_mqttsn_client_search_retry_count',1,'']]],
  ['search_20retry_20period_7',['Configuring &quot;Search&quot; Retry Period',['../index.html#doc_cc_mqttsn_client_search_retry_period',1,'']]],
  ['sending_20connection_20request_8',['Sending Connection Request',['../index.html#doc_cc_mqttsn_client_connect_send',1,'']]],
  ['sending_20data_20to_20gateway_9',['Sending Data To Gateway',['../index.html#doc_cc_mqttsn_client_callbacks_send_data',1,'']]],
  ['sending_20disconnection_20request_10',['Sending Disconnection Request',['../index.html#doc_cc_mqttsn_client_disconnect_send',1,'']]],
  ['sending_20publish_20request_11',['Sending Publish Request',['../index.html#doc_cc_mqttsn_client_publish_send',1,'']]],
  ['sending_20search_20gateway_20request_12',['Sending Search Gateway Request',['../index.html#doc_cc_mqttsn_client_search_send',1,'']]],
  ['sending_20sleep_20request_13',['Sending Sleep Request',['../index.html#doc_cc_mqttsn_client_sleep_send',1,'']]],
  ['sending_20subscription_20request_14',['Sending Subscription Request',['../index.html#doc_cc_mqttsn_client_subscribe_send',1,'']]],
  ['sending_20unsubscription_20request_15',['Sending Unsubscription Request',['../index.html#doc_cc_mqttsn_client_unsubscribe_send',1,'']]],
  ['sending_20will_20update_20request_16',['Sending Will Update Request',['../index.html#doc_cc_mqttsn_client_will_send',1,'']]],
  ['simplifying_20the_20connect_20operation_20preparation_17',['Simplifying the &quot;Connect&quot; Operation Preparation.',['../index.html#doc_cc_mqttsn_client_connect_simplify',1,'']]],
  ['simplifying_20the_20disconnect_20operation_20preparation_18',['Simplifying the &quot;Disconnect&quot; Operation Preparation.',['../index.html#doc_cc_mqttsn_client_disconnect_simplify',1,'']]],
  ['simplifying_20the_20publish_20operation_20preparation_19',['Simplifying the &quot;Publish&quot; Operation Preparation.',['../index.html#doc_cc_mqttsn_client_publish_simplify',1,'']]],
  ['simplifying_20the_20search_20operation_20preparation_20',['Simplifying the &quot;Search&quot; Operation Preparation',['../index.html#doc_cc_mqttsn_client_search_simplify',1,'']]],
  ['simplifying_20the_20sleep_20operation_20preparation_21',['Simplifying the &quot;Sleep&quot; Operation Preparation.',['../index.html#doc_cc_mqttsn_client_sleep_simplify',1,'']]],
  ['simplifying_20the_20subscribe_20operation_20preparation_22',['Simplifying the &quot;Subscribe&quot; Operation Preparation.',['../index.html#doc_cc_mqttsn_client_subscribe_simplify',1,'']]],
  ['simplifying_20the_20unsubscribe_20operation_20preparation_23',['Simplifying the &quot;Unsubscribe&quot; Operation Preparation.',['../index.html#doc_cc_mqttsn_client_unsubscribe_simplify',1,'']]],
  ['simplifying_20the_20will_20operation_20preparation_24',['Simplifying the &quot;Will&quot; Operation Preparation.',['../index.html#doc_cc_mqttsn_client_will_simplify',1,'']]],
  ['sleep_20operation_25',['sleep operation',['../index.html#doc_cc_mqttsn_client_sleep_cancel',1,'Cancel the &quot;Sleep&quot; Operation.'],['../index.html#doc_cc_mqttsn_client_sleep_config',1,'Configuration of &quot;Sleep&quot; Operation'],['../index.html#doc_cc_mqttsn_client_sleep_prepare',1,'Preparing &quot;Sleep&quot; Operation.']]],
  ['sleep_20operation_20preparation_26',['Simplifying the &quot;Sleep&quot; Operation Preparation.',['../index.html#doc_cc_mqttsn_client_sleep_simplify',1,'']]],
  ['sleep_20request_27',['Sending Sleep Request',['../index.html#doc_cc_mqttsn_client_sleep_send',1,'']]],
  ['sleep_20retry_20count_28',['Configuring &quot;Sleep&quot; Retry Count',['../index.html#doc_cc_mqttsn_client_sleep_retry_count',1,'']]],
  ['sleep_20retry_20period_29',['Configuring &quot;Sleep&quot; Retry Period',['../index.html#doc_cc_mqttsn_client_sleep_retry_period',1,'']]],
  ['sleep_20state_30',['Receiving Messages During &quot;Sleep&quot; State.',['../index.html#doc_cc_mqttsn_client_sleep_recv',1,'']]],
  ['sleep_20state_20operation_20data_20types_20and_20functions_31',['&quot;Enter Sleep State Operation Data Types and Functions&quot;',['../group__sleep.html',1,'']]],
  ['sleeping_32',['Sleeping',['../index.html#doc_cc_mqttsn_client_sleep',1,'']]],
  ['sn_20client_20library_33',['MQTT-SN Client Library',['../index.html',1,'']]],
  ['state_34',['Receiving Messages During &quot;Sleep&quot; State.',['../index.html#doc_cc_mqttsn_client_sleep_recv',1,'']]],
  ['state_20operation_20data_20types_20and_20functions_35',['&quot;Enter Sleep State Operation Data Types and Functions&quot;',['../group__sleep.html',1,'']]],
  ['stored_20outgoing_20topic_20ids_36',['Limiting Stored Outgoing Topic IDs',['../index.html#doc_cc_mqttsn_client_publish_reg_limit',1,'']]],
  ['subscribe_20configuration_37',['Subscribe Configuration',['../index.html#doc_cc_mqttsn_client_subscribe_config',1,'']]],
  ['subscribe_20operation_38',['subscribe operation',['../index.html#doc_cc_mqttsn_client_subscribe_cancel',1,'Cancel the &quot;Subscribe&quot; Operation.'],['../index.html#doc_cc_mqttsn_client_subscribe_prepare',1,'Preparing &quot;Subscribe&quot; Operation.']]],
  ['subscribe_20operation_20data_20types_20and_20functions_39',['&quot;Subscribe Operation Data Types and Functions&quot;',['../group__subscribe.html',1,'']]],
  ['subscribe_20operation_20preparation_40',['Simplifying the &quot;Subscribe&quot; Operation Preparation.',['../index.html#doc_cc_mqttsn_client_subscribe_simplify',1,'']]],
  ['subscribe_20retry_20count_41',['Configuring &quot;Subscribe&quot; Retry Count',['../index.html#doc_cc_mqttsn_client_subscribe_retry_count',1,'']]],
  ['subscribe_20retry_20period_42',['Configuring &quot;Subscribe&quot; Retry Period',['../index.html#doc_cc_mqttsn_client_subscribe_retry_period',1,'']]],
  ['subscribing_20to_20receive_20messages_43',['Subscribing to Receive Messages',['../index.html#doc_cc_mqttsn_client_subscribe',1,'']]],
  ['subscription_20request_44',['Sending Subscription Request',['../index.html#doc_cc_mqttsn_client_subscribe_send',1,'']]]
];
