var searchData=
[
  ['period_0',['period',['../index.html#doc_cc_mqttsn_client_connect_retry_period',1,'Configuring &quot;Connect&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_disconnect_retry_period',1,'Configuring &quot;Disconnect&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_publish_retry_period',1,'Configuring &quot;Publish&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_search_retry_period',1,'Configuring &quot;Search&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_sleep_retry_period',1,'Configuring &quot;Sleep&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_subscribe_retry_period',1,'Configuring &quot;Subscribe&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_unsubscribe_retry_period',1,'Configuring &quot;Unsubscribe&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_will_retry_period',1,'Configuring &quot;Will&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_retry_period',1,'Default Retry Period']]],
  ['preparation_1',['preparation',['../index.html#doc_cc_mqttsn_client_connect_simplify',1,'Simplifying the &quot;Connect&quot; Operation Preparation.'],['../index.html#doc_cc_mqttsn_client_disconnect_simplify',1,'Simplifying the &quot;Disconnect&quot; Operation Preparation.'],['../index.html#doc_cc_mqttsn_client_publish_simplify',1,'Simplifying the &quot;Publish&quot; Operation Preparation.'],['../index.html#doc_cc_mqttsn_client_search_simplify',1,'Simplifying the &quot;Search&quot; Operation Preparation'],['../index.html#doc_cc_mqttsn_client_sleep_simplify',1,'Simplifying the &quot;Sleep&quot; Operation Preparation.'],['../index.html#doc_cc_mqttsn_client_subscribe_simplify',1,'Simplifying the &quot;Subscribe&quot; Operation Preparation.'],['../index.html#doc_cc_mqttsn_client_unsubscribe_simplify',1,'Simplifying the &quot;Unsubscribe&quot; Operation Preparation.'],['../index.html#doc_cc_mqttsn_client_will_simplify',1,'Simplifying the &quot;Will&quot; Operation Preparation.']]],
  ['preparing_20connect_20operation_2',['Preparing &quot;Connect&quot; Operation.',['../index.html#doc_cc_mqttsn_client_connect_prepare',1,'']]],
  ['preparing_20disconnect_20operation_3',['Preparing &quot;Disconnect&quot; Operation.',['../index.html#doc_cc_mqttsn_client_disconnect_prepare',1,'']]],
  ['preparing_20publish_20operation_4',['Preparing &quot;Publish&quot; Operation.',['../index.html#doc_cc_mqttsn_client_publish_prepare',1,'']]],
  ['preparing_20search_20operation_5',['Preparing &quot;Search&quot; Operation.',['../index.html#doc_cc_mqttsn_client_search_prepare',1,'']]],
  ['preparing_20sleep_20operation_6',['Preparing &quot;Sleep&quot; Operation.',['../index.html#doc_cc_mqttsn_client_sleep_prepare',1,'']]],
  ['preparing_20subscribe_20operation_7',['Preparing &quot;Subscribe&quot; Operation.',['../index.html#doc_cc_mqttsn_client_subscribe_prepare',1,'']]],
  ['preparing_20unsubscribe_20operation_8',['Preparing &quot;Unsubscribe&quot; Operation.',['../index.html#doc_cc_mqttsn_client_unsubscribe_prepare',1,'']]],
  ['preparing_20will_20operation_9',['Preparing &quot;Will&quot; Operation.',['../index.html#doc_cc_mqttsn_client_will_prepare',1,'']]],
  ['publish_20operation_10',['publish operation',['../index.html#doc_cc_mqttsn_client_publish_cancel',1,'Cancel the &quot;Publish&quot; Operation.'],['../index.html#doc_cc_mqttsn_client_publish_config',1,'Configuration of &quot;Publish&quot; Operation'],['../index.html#doc_cc_mqttsn_client_publish_prepare',1,'Preparing &quot;Publish&quot; Operation.']]],
  ['publish_20operation_20data_20types_20and_20functions_11',['&quot;Publish Operation Data Types and Functions&quot;',['../group__publish.html',1,'']]],
  ['publish_20operation_20preparation_12',['Simplifying the &quot;Publish&quot; Operation Preparation.',['../index.html#doc_cc_mqttsn_client_publish_simplify',1,'']]],
  ['publish_20request_13',['Sending Publish Request',['../index.html#doc_cc_mqttsn_client_publish_send',1,'']]],
  ['publish_20retry_20count_14',['Configuring &quot;Publish&quot; Retry Count',['../index.html#doc_cc_mqttsn_client_publish_retry_count',1,'']]],
  ['publish_20retry_20period_15',['Configuring &quot;Publish&quot; Retry Period',['../index.html#doc_cc_mqttsn_client_publish_retry_period',1,'']]],
  ['publishing_20messages_16',['Publishing Messages',['../index.html#doc_cc_mqttsn_client_publish',1,'']]]
];
