var searchData=
[
  ['radius_0',['radius',['../index.html#doc_cc_mqttsn_client_search_broadcast_radius',1,'Configuring &quot;Search&quot; Broadcast Radius'],['../index.html#doc_cc_mqttsn_client_broadcast_radius',1,'Default Broadcast Radius']]],
  ['receive_20messages_1',['Subscribing to Receive Messages',['../index.html#doc_cc_mqttsn_client_subscribe',1,'']]],
  ['received_20message_2',['Reporting Received Message',['../index.html#doc_cc_mqttsn_client_callbacks_message',1,'']]],
  ['receiving_20disconnect_20message_3',['Receiving DISCONNECT message',['../index.html#doc_cc_mqttsn_client_unsolicited_disconnect_message',1,'']]],
  ['receiving_20messages_4',['receiving messages',['../index.html#doc_cc_mqttsn_client_receive',1,'Receiving Messages'],['../index.html#doc_cc_mqttsn_client_unsubscribe',1,'Unsubscribing from Receiving Messages']]],
  ['receiving_20messages_20during_20sleep_20state_5',['Receiving Messages During &quot;Sleep&quot; State.',['../index.html#doc_cc_mqttsn_client_sleep_recv',1,'']]],
  ['registration_6',['&quot;Must Have&quot; Callbacks Registration',['../index.html#doc_cc_mqttsn_client_callbacks',1,'']]],
  ['remains_20connected_7',['Check The Library Remains Connected',['../index.html#doc_cc_mqttsn_client_connect_check',1,'']]],
  ['reporting_20incoming_20data_8',['Reporting Incoming Data',['../index.html#doc_cc_mqttsn_client_data',1,'']]],
  ['reporting_20received_20message_9',['Reporting Received Message',['../index.html#doc_cc_mqttsn_client_callbacks_message',1,'']]],
  ['reporting_20unsolicited_20gateway_20disconnection_10',['Reporting Unsolicited Gateway Disconnection',['../index.html#doc_cc_mqttsn_client_callbacks_gateway_disconnect',1,'']]],
  ['request_11',['request',['../index.html#doc_cc_mqttsn_client_connect_send',1,'Sending Connection Request'],['../index.html#doc_cc_mqttsn_client_disconnect_send',1,'Sending Disconnection Request'],['../index.html#doc_cc_mqttsn_client_publish_send',1,'Sending Publish Request'],['../index.html#doc_cc_mqttsn_client_search_send',1,'Sending Search Gateway Request'],['../index.html#doc_cc_mqttsn_client_sleep_send',1,'Sending Sleep Request'],['../index.html#doc_cc_mqttsn_client_subscribe_send',1,'Sending Subscription Request'],['../index.html#doc_cc_mqttsn_client_unsubscribe_send',1,'Sending Unsubscription Request'],['../index.html#doc_cc_mqttsn_client_will_send',1,'Sending Will Update Request']]],
  ['retry_20count_12',['retry count',['../index.html#doc_cc_mqttsn_client_connect_retry_count',1,'Configuring &quot;Connect&quot; Retry Count'],['../index.html#doc_cc_mqttsn_client_disconnect_retry_count',1,'Configuring &quot;Disconnect&quot; Retry Count'],['../index.html#doc_cc_mqttsn_client_publish_retry_count',1,'Configuring &quot;Publish&quot; Retry Count'],['../index.html#doc_cc_mqttsn_client_search_retry_count',1,'Configuring &quot;Search&quot; Retry Count'],['../index.html#doc_cc_mqttsn_client_sleep_retry_count',1,'Configuring &quot;Sleep&quot; Retry Count'],['../index.html#doc_cc_mqttsn_client_subscribe_retry_count',1,'Configuring &quot;Subscribe&quot; Retry Count'],['../index.html#doc_cc_mqttsn_client_unsubscribe_retry_count',1,'Configuring &quot;Unsubscribe&quot; Retry Count'],['../index.html#doc_cc_mqttsn_client_will_retry_count',1,'Configuring &quot;Will&quot; Retry Count'],['../index.html#doc_cc_mqttsn_client_retry_count',1,'Default Retry Count']]],
  ['retry_20period_13',['retry period',['../index.html#doc_cc_mqttsn_client_connect_retry_period',1,'Configuring &quot;Connect&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_disconnect_retry_period',1,'Configuring &quot;Disconnect&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_publish_retry_period',1,'Configuring &quot;Publish&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_search_retry_period',1,'Configuring &quot;Search&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_sleep_retry_period',1,'Configuring &quot;Sleep&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_subscribe_retry_period',1,'Configuring &quot;Subscribe&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_unsubscribe_retry_period',1,'Configuring &quot;Unsubscribe&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_will_retry_period',1,'Configuring &quot;Will&quot; Retry Period'],['../index.html#doc_cc_mqttsn_client_retry_period',1,'Default Retry Period']]]
];
